### ISSUE TITLE
Multiple selectors override each other. 

### ISSUE THREAD

**Issue by itzikbenh** [corysimmons/postcss-ant#11]
First, thank you for creating this great package. I come from bootstrap where there's no such thing as gutters :) 

Not sure if this is intentional or not, but I can't use multiple selectors. 

```SCSS
//company-information overrides create-login. 
.create-login, .company-information {
	gg: columns(1/2 1/2)  gutters(100px, 10px);
}

//An example of the compiled code
#register .create-login, #register .company-information > *:nth-child(n + 3) {
	margin-top: 10px; 
}
```
If I separate them then it will work just fine. 
Just wanted to make sure it's okay.

Sorry if this is something obvious that I missed.
